/*
  # Add Rack Locations A1-K30 for INPUT_KELUAR

  1. New Data
    - Adding 330 rack locations (A1-A30, B1-B30, C1-C30, D1-D30, E1-E30, F1-F30, G1-G30, H1-H30, I1-I30, J1-J30, K1-K30)
    - All locations set to display in INPUT_KELUAR menu only
    - All locations set to Aktif status

  2. Security
    - Uses existing RLS policies on rack_locations table
*/

-- Insert rack locations A1-A30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('A1', 'INPUT_KELUAR', 'Aktif'),
('A2', 'INPUT_KELUAR', 'Aktif'),
('A3', 'INPUT_KELUAR', 'Aktif'),
('A4', 'INPUT_KELUAR', 'Aktif'),
('A5', 'INPUT_KELUAR', 'Aktif'),
('A6', 'INPUT_KELUAR', 'Aktif'),
('A7', 'INPUT_KELUAR', 'Aktif'),
('A8', 'INPUT_KELUAR', 'Aktif'),
('A9', 'INPUT_KELUAR', 'Aktif'),
('A10', 'INPUT_KELUAR', 'Aktif'),
('A11', 'INPUT_KELUAR', 'Aktif'),
('A12', 'INPUT_KELUAR', 'Aktif'),
('A13', 'INPUT_KELUAR', 'Aktif'),
('A14', 'INPUT_KELUAR', 'Aktif'),
('A15', 'INPUT_KELUAR', 'Aktif'),
('A16', 'INPUT_KELUAR', 'Aktif'),
('A17', 'INPUT_KELUAR', 'Aktif'),
('A18', 'INPUT_KELUAR', 'Aktif'),
('A19', 'INPUT_KELUAR', 'Aktif'),
('A20', 'INPUT_KELUAR', 'Aktif'),
('A21', 'INPUT_KELUAR', 'Aktif'),
('A22', 'INPUT_KELUAR', 'Aktif'),
('A23', 'INPUT_KELUAR', 'Aktif'),
('A24', 'INPUT_KELUAR', 'Aktif'),
('A25', 'INPUT_KELUAR', 'Aktif'),
('A26', 'INPUT_KELUAR', 'Aktif'),
('A27', 'INPUT_KELUAR', 'Aktif'),
('A28', 'INPUT_KELUAR', 'Aktif'),
('A29', 'INPUT_KELUAR', 'Aktif'),
('A30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations B1-B30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('B1', 'INPUT_KELUAR', 'Aktif'),
('B2', 'INPUT_KELUAR', 'Aktif'),
('B3', 'INPUT_KELUAR', 'Aktif'),
('B4', 'INPUT_KELUAR', 'Aktif'),
('B5', 'INPUT_KELUAR', 'Aktif'),
('B6', 'INPUT_KELUAR', 'Aktif'),
('B7', 'INPUT_KELUAR', 'Aktif'),
('B8', 'INPUT_KELUAR', 'Aktif'),
('B9', 'INPUT_KELUAR', 'Aktif'),
('B10', 'INPUT_KELUAR', 'Aktif'),
('B11', 'INPUT_KELUAR', 'Aktif'),
('B12', 'INPUT_KELUAR', 'Aktif'),
('B13', 'INPUT_KELUAR', 'Aktif'),
('B14', 'INPUT_KELUAR', 'Aktif'),
('B15', 'INPUT_KELUAR', 'Aktif'),
('B16', 'INPUT_KELUAR', 'Aktif'),
('B17', 'INPUT_KELUAR', 'Aktif'),
('B18', 'INPUT_KELUAR', 'Aktif'),
('B19', 'INPUT_KELUAR', 'Aktif'),
('B20', 'INPUT_KELUAR', 'Aktif'),
('B21', 'INPUT_KELUAR', 'Aktif'),
('B22', 'INPUT_KELUAR', 'Aktif'),
('B23', 'INPUT_KELUAR', 'Aktif'),
('B24', 'INPUT_KELUAR', 'Aktif'),
('B25', 'INPUT_KELUAR', 'Aktif'),
('B26', 'INPUT_KELUAR', 'Aktif'),
('B27', 'INPUT_KELUAR', 'Aktif'),
('B28', 'INPUT_KELUAR', 'Aktif'),
('B29', 'INPUT_KELUAR', 'Aktif'),
('B30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations C1-C30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('C1', 'INPUT_KELUAR', 'Aktif'),
('C2', 'INPUT_KELUAR', 'Aktif'),
('C3', 'INPUT_KELUAR', 'Aktif'),
('C4', 'INPUT_KELUAR', 'Aktif'),
('C5', 'INPUT_KELUAR', 'Aktif'),
('C6', 'INPUT_KELUAR', 'Aktif'),
('C7', 'INPUT_KELUAR', 'Aktif'),
('C8', 'INPUT_KELUAR', 'Aktif'),
('C9', 'INPUT_KELUAR', 'Aktif'),
('C10', 'INPUT_KELUAR', 'Aktif'),
('C11', 'INPUT_KELUAR', 'Aktif'),
('C12', 'INPUT_KELUAR', 'Aktif'),
('C13', 'INPUT_KELUAR', 'Aktif'),
('C14', 'INPUT_KELUAR', 'Aktif'),
('C15', 'INPUT_KELUAR', 'Aktif'),
('C16', 'INPUT_KELUAR', 'Aktif'),
('C17', 'INPUT_KELUAR', 'Aktif'),
('C18', 'INPUT_KELUAR', 'Aktif'),
('C19', 'INPUT_KELUAR', 'Aktif'),
('C20', 'INPUT_KELUAR', 'Aktif'),
('C21', 'INPUT_KELUAR', 'Aktif'),
('C22', 'INPUT_KELUAR', 'Aktif'),
('C23', 'INPUT_KELUAR', 'Aktif'),
('C24', 'INPUT_KELUAR', 'Aktif'),
('C25', 'INPUT_KELUAR', 'Aktif'),
('C26', 'INPUT_KELUAR', 'Aktif'),
('C27', 'INPUT_KELUAR', 'Aktif'),
('C28', 'INPUT_KELUAR', 'Aktif'),
('C29', 'INPUT_KELUAR', 'Aktif'),
('C30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations D1-D30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('D1', 'INPUT_KELUAR', 'Aktif'),
('D2', 'INPUT_KELUAR', 'Aktif'),
('D3', 'INPUT_KELUAR', 'Aktif'),
('D4', 'INPUT_KELUAR', 'Aktif'),
('D5', 'INPUT_KELUAR', 'Aktif'),
('D6', 'INPUT_KELUAR', 'Aktif'),
('D7', 'INPUT_KELUAR', 'Aktif'),
('D8', 'INPUT_KELUAR', 'Aktif'),
('D9', 'INPUT_KELUAR', 'Aktif'),
('D10', 'INPUT_KELUAR', 'Aktif'),
('D11', 'INPUT_KELUAR', 'Aktif'),
('D12', 'INPUT_KELUAR', 'Aktif'),
('D13', 'INPUT_KELUAR', 'Aktif'),
('D14', 'INPUT_KELUAR', 'Aktif'),
('D15', 'INPUT_KELUAR', 'Aktif'),
('D16', 'INPUT_KELUAR', 'Aktif'),
('D17', 'INPUT_KELUAR', 'Aktif'),
('D18', 'INPUT_KELUAR', 'Aktif'),
('D19', 'INPUT_KELUAR', 'Aktif'),
('D20', 'INPUT_KELUAR', 'Aktif'),
('D21', 'INPUT_KELUAR', 'Aktif'),
('D22', 'INPUT_KELUAR', 'Aktif'),
('D23', 'INPUT_KELUAR', 'Aktif'),
('D24', 'INPUT_KELUAR', 'Aktif'),
('D25', 'INPUT_KELUAR', 'Aktif'),
('D26', 'INPUT_KELUAR', 'Aktif'),
('D27', 'INPUT_KELUAR', 'Aktif'),
('D28', 'INPUT_KELUAR', 'Aktif'),
('D29', 'INPUT_KELUAR', 'Aktif'),
('D30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations E1-E30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('E1', 'INPUT_KELUAR', 'Aktif'),
('E2', 'INPUT_KELUAR', 'Aktif'),
('E3', 'INPUT_KELUAR', 'Aktif'),
('E4', 'INPUT_KELUAR', 'Aktif'),
('E5', 'INPUT_KELUAR', 'Aktif'),
('E6', 'INPUT_KELUAR', 'Aktif'),
('E7', 'INPUT_KELUAR', 'Aktif'),
('E8', 'INPUT_KELUAR', 'Aktif'),
('E9', 'INPUT_KELUAR', 'Aktif'),
('E10', 'INPUT_KELUAR', 'Aktif'),
('E11', 'INPUT_KELUAR', 'Aktif'),
('E12', 'INPUT_KELUAR', 'Aktif'),
('E13', 'INPUT_KELUAR', 'Aktif'),
('E14', 'INPUT_KELUAR', 'Aktif'),
('E15', 'INPUT_KELUAR', 'Aktif'),
('E16', 'INPUT_KELUAR', 'Aktif'),
('E17', 'INPUT_KELUAR', 'Aktif'),
('E18', 'INPUT_KELUAR', 'Aktif'),
('E19', 'INPUT_KELUAR', 'Aktif'),
('E20', 'INPUT_KELUAR', 'Aktif'),
('E21', 'INPUT_KELUAR', 'Aktif'),
('E22', 'INPUT_KELUAR', 'Aktif'),
('E23', 'INPUT_KELUAR', 'Aktif'),
('E24', 'INPUT_KELUAR', 'Aktif'),
('E25', 'INPUT_KELUAR', 'Aktif'),
('E26', 'INPUT_KELUAR', 'Aktif'),
('E27', 'INPUT_KELUAR', 'Aktif'),
('E28', 'INPUT_KELUAR', 'Aktif'),
('E29', 'INPUT_KELUAR', 'Aktif'),
('E30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations F1-F30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('F1', 'INPUT_KELUAR', 'Aktif'),
('F2', 'INPUT_KELUAR', 'Aktif'),
('F3', 'INPUT_KELUAR', 'Aktif'),
('F4', 'INPUT_KELUAR', 'Aktif'),
('F5', 'INPUT_KELUAR', 'Aktif'),
('F6', 'INPUT_KELUAR', 'Aktif'),
('F7', 'INPUT_KELUAR', 'Aktif'),
('F8', 'INPUT_KELUAR', 'Aktif'),
('F9', 'INPUT_KELUAR', 'Aktif'),
('F10', 'INPUT_KELUAR', 'Aktif'),
('F11', 'INPUT_KELUAR', 'Aktif'),
('F12', 'INPUT_KELUAR', 'Aktif'),
('F13', 'INPUT_KELUAR', 'Aktif'),
('F14', 'INPUT_KELUAR', 'Aktif'),
('F15', 'INPUT_KELUAR', 'Aktif'),
('F16', 'INPUT_KELUAR', 'Aktif'),
('F17', 'INPUT_KELUAR', 'Aktif'),
('F18', 'INPUT_KELUAR', 'Aktif'),
('F19', 'INPUT_KELUAR', 'Aktif'),
('F20', 'INPUT_KELUAR', 'Aktif'),
('F21', 'INPUT_KELUAR', 'Aktif'),
('F22', 'INPUT_KELUAR', 'Aktif'),
('F23', 'INPUT_KELUAR', 'Aktif'),
('F24', 'INPUT_KELUAR', 'Aktif'),
('F25', 'INPUT_KELUAR', 'Aktif'),
('F26', 'INPUT_KELUAR', 'Aktif'),
('F27', 'INPUT_KELUAR', 'Aktif'),
('F28', 'INPUT_KELUAR', 'Aktif'),
('F29', 'INPUT_KELUAR', 'Aktif'),
('F30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations G1-G30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('G1', 'INPUT_KELUAR', 'Aktif'),
('G2', 'INPUT_KELUAR', 'Aktif'),
('G3', 'INPUT_KELUAR', 'Aktif'),
('G4', 'INPUT_KELUAR', 'Aktif'),
('G5', 'INPUT_KELUAR', 'Aktif'),
('G6', 'INPUT_KELUAR', 'Aktif'),
('G7', 'INPUT_KELUAR', 'Aktif'),
('G8', 'INPUT_KELUAR', 'Aktif'),
('G9', 'INPUT_KELUAR', 'Aktif'),
('G10', 'INPUT_KELUAR', 'Aktif'),
('G11', 'INPUT_KELUAR', 'Aktif'),
('G12', 'INPUT_KELUAR', 'Aktif'),
('G13', 'INPUT_KELUAR', 'Aktif'),
('G14', 'INPUT_KELUAR', 'Aktif'),
('G15', 'INPUT_KELUAR', 'Aktif'),
('G16', 'INPUT_KELUAR', 'Aktif'),
('G17', 'INPUT_KELUAR', 'Aktif'),
('G18', 'INPUT_KELUAR', 'Aktif'),
('G19', 'INPUT_KELUAR', 'Aktif'),
('G20', 'INPUT_KELUAR', 'Aktif'),
('G21', 'INPUT_KELUAR', 'Aktif'),
('G22', 'INPUT_KELUAR', 'Aktif'),
('G23', 'INPUT_KELUAR', 'Aktif'),
('G24', 'INPUT_KELUAR', 'Aktif'),
('G25', 'INPUT_KELUAR', 'Aktif'),
('G26', 'INPUT_KELUAR', 'Aktif'),
('G27', 'INPUT_KELUAR', 'Aktif'),
('G28', 'INPUT_KELUAR', 'Aktif'),
('G29', 'INPUT_KELUAR', 'Aktif'),
('G30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations H1-H30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('H1', 'INPUT_KELUAR', 'Aktif'),
('H2', 'INPUT_KELUAR', 'Aktif'),
('H3', 'INPUT_KELUAR', 'Aktif'),
('H4', 'INPUT_KELUAR', 'Aktif'),
('H5', 'INPUT_KELUAR', 'Aktif'),
('H6', 'INPUT_KELUAR', 'Aktif'),
('H7', 'INPUT_KELUAR', 'Aktif'),
('H8', 'INPUT_KELUAR', 'Aktif'),
('H9', 'INPUT_KELUAR', 'Aktif'),
('H10', 'INPUT_KELUAR', 'Aktif'),
('H11', 'INPUT_KELUAR', 'Aktif'),
('H12', 'INPUT_KELUAR', 'Aktif'),
('H13', 'INPUT_KELUAR', 'Aktif'),
('H14', 'INPUT_KELUAR', 'Aktif'),
('H15', 'INPUT_KELUAR', 'Aktif'),
('H16', 'INPUT_KELUAR', 'Aktif'),
('H17', 'INPUT_KELUAR', 'Aktif'),
('H18', 'INPUT_KELUAR', 'Aktif'),
('H19', 'INPUT_KELUAR', 'Aktif'),
('H20', 'INPUT_KELUAR', 'Aktif'),
('H21', 'INPUT_KELUAR', 'Aktif'),
('H22', 'INPUT_KELUAR', 'Aktif'),
('H23', 'INPUT_KELUAR', 'Aktif'),
('H24', 'INPUT_KELUAR', 'Aktif'),
('H25', 'INPUT_KELUAR', 'Aktif'),
('H26', 'INPUT_KELUAR', 'Aktif'),
('H27', 'INPUT_KELUAR', 'Aktif'),
('H28', 'INPUT_KELUAR', 'Aktif'),
('H29', 'INPUT_KELUAR', 'Aktif'),
('H30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations I1-I30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('I1', 'INPUT_KELUAR', 'Aktif'),
('I2', 'INPUT_KELUAR', 'Aktif'),
('I3', 'INPUT_KELUAR', 'Aktif'),
('I4', 'INPUT_KELUAR', 'Aktif'),
('I5', 'INPUT_KELUAR', 'Aktif'),
('I6', 'INPUT_KELUAR', 'Aktif'),
('I7', 'INPUT_KELUAR', 'Aktif'),
('I8', 'INPUT_KELUAR', 'Aktif'),
('I9', 'INPUT_KELUAR', 'Aktif'),
('I10', 'INPUT_KELUAR', 'Aktif'),
('I11', 'INPUT_KELUAR', 'Aktif'),
('I12', 'INPUT_KELUAR', 'Aktif'),
('I13', 'INPUT_KELUAR', 'Aktif'),
('I14', 'INPUT_KELUAR', 'Aktif'),
('I15', 'INPUT_KELUAR', 'Aktif'),
('I16', 'INPUT_KELUAR', 'Aktif'),
('I17', 'INPUT_KELUAR', 'Aktif'),
('I18', 'INPUT_KELUAR', 'Aktif'),
('I19', 'INPUT_KELUAR', 'Aktif'),
('I20', 'INPUT_KELUAR', 'Aktif'),
('I21', 'INPUT_KELUAR', 'Aktif'),
('I22', 'INPUT_KELUAR', 'Aktif'),
('I23', 'INPUT_KELUAR', 'Aktif'),
('I24', 'INPUT_KELUAR', 'Aktif'),
('I25', 'INPUT_KELUAR', 'Aktif'),
('I26', 'INPUT_KELUAR', 'Aktif'),
('I27', 'INPUT_KELUAR', 'Aktif'),
('I28', 'INPUT_KELUAR', 'Aktif'),
('I29', 'INPUT_KELUAR', 'Aktif'),
('I30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations J1-J30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('J1', 'INPUT_KELUAR', 'Aktif'),
('J2', 'INPUT_KELUAR', 'Aktif'),
('J3', 'INPUT_KELUAR', 'Aktif'),
('J4', 'INPUT_KELUAR', 'Aktif'),
('J5', 'INPUT_KELUAR', 'Aktif'),
('J6', 'INPUT_KELUAR', 'Aktif'),
('J7', 'INPUT_KELUAR', 'Aktif'),
('J8', 'INPUT_KELUAR', 'Aktif'),
('J9', 'INPUT_KELUAR', 'Aktif'),
('J10', 'INPUT_KELUAR', 'Aktif'),
('J11', 'INPUT_KELUAR', 'Aktif'),
('J12', 'INPUT_KELUAR', 'Aktif'),
('J13', 'INPUT_KELUAR', 'Aktif'),
('J14', 'INPUT_KELUAR', 'Aktif'),
('J15', 'INPUT_KELUAR', 'Aktif'),
('J16', 'INPUT_KELUAR', 'Aktif'),
('J17', 'INPUT_KELUAR', 'Aktif'),
('J18', 'INPUT_KELUAR', 'Aktif'),
('J19', 'INPUT_KELUAR', 'Aktif'),
('J20', 'INPUT_KELUAR', 'Aktif'),
('J21', 'INPUT_KELUAR', 'Aktif'),
('J22', 'INPUT_KELUAR', 'Aktif'),
('J23', 'INPUT_KELUAR', 'Aktif'),
('J24', 'INPUT_KELUAR', 'Aktif'),
('J25', 'INPUT_KELUAR', 'Aktif'),
('J26', 'INPUT_KELUAR', 'Aktif'),
('J27', 'INPUT_KELUAR', 'Aktif'),
('J28', 'INPUT_KELUAR', 'Aktif'),
('J29', 'INPUT_KELUAR', 'Aktif'),
('J30', 'INPUT_KELUAR', 'Aktif');

-- Insert rack locations K1-K30
INSERT INTO rack_locations (nama, tampil_di_menu, status) VALUES
('K1', 'INPUT_KELUAR', 'Aktif'),
('K2', 'INPUT_KELUAR', 'Aktif'),
('K3', 'INPUT_KELUAR', 'Aktif'),
('K4', 'INPUT_KELUAR', 'Aktif'),
('K5', 'INPUT_KELUAR', 'Aktif'),
('K6', 'INPUT_KELUAR', 'Aktif'),
('K7', 'INPUT_KELUAR', 'Aktif'),
('K8', 'INPUT_KELUAR', 'Aktif'),
('K9', 'INPUT_KELUAR', 'Aktif'),
('K10', 'INPUT_KELUAR', 'Aktif'),
('K11', 'INPUT_KELUAR', 'Aktif'),
('K12', 'INPUT_KELUAR', 'Aktif'),
('K13', 'INPUT_KELUAR', 'Aktif'),
('K14', 'INPUT_KELUAR', 'Aktif'),
('K15', 'INPUT_KELUAR', 'Aktif'),
('K16', 'INPUT_KELUAR', 'Aktif'),
('K17', 'INPUT_KELUAR', 'Aktif'),
('K18', 'INPUT_KELUAR', 'Aktif'),
('K19', 'INPUT_KELUAR', 'Aktif'),
('K20', 'INPUT_KELUAR', 'Aktif'),
('K21', 'INPUT_KELUAR', 'Aktif'),
('K22', 'INPUT_KELUAR', 'Aktif'),
('K23', 'INPUT_KELUAR', 'Aktif'),
('K24', 'INPUT_KELUAR', 'Aktif'),
('K25', 'INPUT_KELUAR', 'Aktif'),
('K26', 'INPUT_KELUAR', 'Aktif'),
('K27', 'INPUT_KELUAR', 'Aktif'),
('K28', 'INPUT_KELUAR', 'Aktif'),
('K29', 'INPUT_KELUAR', 'Aktif'),
('K30', 'INPUT_KELUAR', 'Aktif');